server:
  port: 8090

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create

  datasource:
    url: jdbc:h2:file:C:\Estudos\BD\springboot-konquest
    driverClassName: org.h2.Driver
    username: sa
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
          trace: false
          web-allow-others: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher